### ISSUE TITLE
不能同时开启两个hp内网穿透

### ISSUE THREAD

**Issue by 0zjn0123** [heixiaoma/hp#2]
如题
![Screenshot_20240615_223327](https://github.com/heixiaoma/hp/assets/116432703/e49d4318-9f22-41f9-b4b1-869a3fe4dc6b)

**Comment by heixiaoma** [comment]
你目前使用的hppro版本，同时这个问题是DNS解析问题，可以尝试配置你的DNS服务器 位于 /etc/resolv.conf 添加nameserver

**Comment by 0zjn0123** [comment]
> 你目前使用的hppro版本，同时这个问题是DNS解析问题，可以尝试配置你的DNS服务器 位于 /etc/resolv.conf 添加nameserver

我使用的是最新的hppro从官网上下载的，该怎么配置DNS服务器？

**Comment by heixiaoma** [comment]
文件位于，
/etc/resolv.conf
nameserver    223.5.5.5

**Comment by heixiaoma** [comment]
具体可以，加入qq交流群聊

**Comment by heixiaoma** [comment]
点击链接加入群聊【HP映射交流群3群】：http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=DqCBGMg-dKDlkjTh3MSvI9oxN2Gs_1o1&authKey=2we%2FJqqB9B9UetGFXEzSx7kzWfIf28sYTsIkGwx22X7iuTQovpEzuwm3a%2BDAIazy&noverify=0&group_code=694209653

**Comment by heixiaoma** [comment]
golang语言中，通过路由器解析DNS失败后，会走本机/etc/resolv.conf文件里读取nameserver dns服务器解析解析
